import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.concurrent.atomic.AtomicBoolean;
import java.awt.event.ActionEvent;
import java.time.temporal.ChronoUnit;
import java.util.Locale;

public class PenghitungUmurFrame extends javax.swing.JFrame {
    private final PenghitungUmurHelper helper;
    private Thread peristiwaThread; 
    private final AtomicBoolean stopFetching = new AtomicBoolean(false);

    public PenghitungUmurFrame() {
        initComponents();
        helper = new PenghitungUmurHelper();
        
        jTextArea1.setEditable(false);
        jTextFieldUmur.setEditable(false); // Umur Saat Ini
        txtBerikutnya.setEditable(false); // Ulang Tahun Berikutnya
    }

    // Metode untuk menghentikan thread pengambilan peristiwa jika sedang berjalan
    private void stopPeristiwaThread() {
        if (peristiwaThread != null && peristiwaThread.isAlive()) {
            stopFetching.set(true);
            peristiwaThread.interrupt();
            peristiwaThread = null;
        }
        stopFetching.set(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TngglLahir = new javax.swing.JLabel();
        UmurAnda = new javax.swing.JLabel();
        UltahBerikutnya = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextFieldUmur = new javax.swing.JTextField();
        txtBerikutnya = new javax.swing.JTextField();
        btnHitungUmur = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtAreaPeristiwa = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PeristiwaPenting = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APLIKASI PENGHITUNG UMUR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        TngglLahir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TngglLahir.setForeground(new java.awt.Color(255, 255, 255));
        TngglLahir.setText("Pilih Tanggal Lahir");

        UmurAnda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UmurAnda.setForeground(new java.awt.Color(255, 255, 255));
        UmurAnda.setText("Umur Anda");

        UltahBerikutnya.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UltahBerikutnya.setForeground(new java.awt.Color(255, 255, 255));
        UltahBerikutnya.setText("Hari Ulang Tahun Berikutnya");

        jDateChooser1.setBackground(new java.awt.Color(0, 255, 204));
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        txtBerikutnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBerikutnyaActionPerformed(evt);
            }
        });

        btnHitungUmur.setBackground(new java.awt.Color(255, 255, 153));
        btnHitungUmur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHitungUmur.setText("Hitung Umur");
        btnHitungUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungUmurActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(255, 255, 153));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txtAreaPeristiwa.setViewportView(jTextArea1);

        PeristiwaPenting.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PeristiwaPenting.setText("Peristiwa Penting");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAreaPeristiwa, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(PeristiwaPenting)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(PeristiwaPenting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAreaPeristiwa, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnHitungUmur, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UltahBerikutnya)
                            .addComponent(TngglLahir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UmurAnda, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldUmur)
                            .addComponent(txtBerikutnya, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TngglLahir)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UmurAnda)
                    .addComponent(jTextFieldUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UltahBerikutnya)
                    .addComponent(txtBerikutnya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHitungUmur, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnHitungUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungUmurActionPerformed
        Date inputDate = jDateChooser1.getDate();

        // Hentikan thread peristiwa lama
        stopPeristiwaThread();

        if (inputDate == null) {
            JOptionPane.showMessageDialog(this, "Mohon pilih Tanggal Lahir terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            LocalDate tglLahir = inputDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            // Konversi Date dari JDateChooser ke LocalDate
            LocalDate tglSekarang = LocalDate.now();

            if (tglLahir.isAfter(tglSekarang)) {
                JOptionPane.showMessageDialog(this, "Tanggal lahir tidak boleh melebihi tanggal hari ini.", "Error Input", JOptionPane.ERROR_MESSAGE);
                // Bersihkan output jika ada error
                jTextFieldUmur.setText("");
                txtBerikutnya.setText("");
                return;
            }

            // 1. Hitung Umur Saat Ini (Output jTextField1)
            String umurDetail = helper.hitungUmurDetail(tglLahir, tglSekarang);
            jTextFieldUmur.setText(umurDetail);

            // 2. Hitung Ulang Tahun Berikutnya (Output jTextField2)
            LocalDate ultahBerikutnya = helper.hariUlangTahunBerikutnya(tglLahir, tglSekarang);

            // Hitung sisa bulan dan hari
            Period sisaWaktu = Period.between(tglSekarang, ultahBerikutnya);

            String hariUltah = helper.getDayOfWeekInIndonesian(ultahBerikutnya);

            // Format tanggal menggunakan Locale Indonesia (agar bulan tercetak dalam B. Indonesia)
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMMM yyyy", new Locale("id", "ID"));

            String ultahStr = String.format("%s, %s (sisa %d bulan %d hari)",
                ultahBerikutnya.format(formatter),
                hariUltah,
                sisaWaktu.getMonths(),
                sisaWaktu.getDays());

            txtBerikutnya.setText(ultahStr);

            try {
                int month = tglLahir.getMonthValue();
                int day = tglLahir.getDayOfMonth();

                jTextArea1.setText("Mengambil peristiwa penting pada tanggal " + day + " " + tglLahir.getMonth() + "...\n");

                // 4. Jalankan pengambilan data dalam thread baru
                new Thread(() -> {
                    helper.fetchPeristiwaPenting(month, day, jTextArea1, () -> false);
                }).start();

            } catch (Exception e) {
                jTextArea1.setText("Gagal mengambil data: " + e.getMessage());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghitung umur. Pastikan input benar. Error: " + e.getMessage(), "Error Perhitungan", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        // TODO add your handling code here:

    }//GEN-LAST:event_btnHitungUmurActionPerformed

    private void txtBerikutnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBerikutnyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBerikutnyaActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        if ("date".equals(evt.getPropertyName())) {
            jTextFieldUmur.setText("");
            txtBerikutnya.setText("");
            jTextArea1.setText("");
            stopPeristiwaThread();
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

/**
     * Main method
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(PenghitungUmurFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new PenghitungUmurFrame().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PeristiwaPenting;
    private javax.swing.JLabel TngglLahir;
    private javax.swing.JLabel UltahBerikutnya;
    private javax.swing.JLabel UmurAnda;
    private javax.swing.JButton btnHitungUmur;
    private javax.swing.JButton btnKeluar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldUmur;
    private javax.swing.JScrollPane txtAreaPeristiwa;
    private javax.swing.JTextField txtBerikutnya;
    // End of variables declaration//GEN-END:variables
}